### PR TITLE
Profile Side Menu Component 

### PR DESCRIPTION
**Pull request by keikeka**

### CODE REVIEW

**Comment by keikeka** [comment]
Creation of styles for component, component ready for review. Tentatively has typography parameters but for its visualization, then they will be modified by the tokens. 
I have doubts about the modification of the Collapse Icon. 
I await your comments to make the corresponding adjustments.

**Review by OvidioSantoro — APPROVED** [review]
Everything seems fine to me. There will be some issues with sizes and margins in all the side menus but that's not something you should be concerned. 

We will solve it when the whole view is finished and we put everything together, to have the exact same properties on all elements, as we're all adjusting the elements in a slightly different way.

Good work!

**Comment by OvidioSantoro** [comment]
By the way, you forgot to pull the changes done to develop before pushing the Pull Request and it had conflicts. I have resolved them myself, but be careful with that ;)

**Review by AslanSN — APPROVED** [review]

**Comment by keikeka** [comment]
Great, thank you very much for the review, at least this part of the work done, when the views are done we will correct all the properties, to leave everything well organized. 

Yes, I had done pull but not the last one, that's why the conflicts jumped. I will keep this in mind for the next one and sorry for the mistake.

**Pull request merged**
